spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer