spring:
  config:
    activate:
      on-profile: local
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8087

---
spring:
  config:
    activate:
      on-profile: kubernetes
  kafka:
    producer:
      bootstrap-servers: kafka.develop.svc.cluster.local:9092
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8087