apiVersion: apps/v1
kind: Deployment
metadata:
  name: springkafkamockdata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springkafkamockdata
  template:
    metadata:
      labels:
        app: springkafkamockdata
    spec:
      containers:
      - name: springkafkamockdata
        image: doomthedocker/springkafkamockdata:latest  # Assure-toi que ce chemin est correct
        ports:
        - containerPort: 8087
