apiVersion: v1
kind: Service
metadata:
  name: springkafkamockdata-service
spec:
  selector:
    app: springkafkamockdata
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8087 # Cela doit correspondre au port de votre application à l'intérieur du conteneur
  type: LoadBalancer # Vous pouvez choisir NodePort ou ClusterIP en fonction de vos besoins
