apiVersion: v1
kind: Service
metadata:
  name: springkafkamockdata-service
spec:
  selector:
    app: springkafkamockdata
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8087
      nodePort: 30007 # Port accessible depuis l'extérieur
  type: NodePort

