apiVersion: v1
kind: Service
metadata:
  name: springkafkamockdata-service
spec:
  selector:
    app: springkafkamockdata
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8087 # Correspond au port de l'application dans le pod
  type: ClusterIP
