spring:
  kafka:
    producer:
      bootstrap-servers: kafka:9092  # Remplace localhost par le nom du service Kafka dans Kubernetes
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8087